[tool.poetry]
name = "niapy"
version = "2.0.5"
description = "Python micro framework for building nature-inspired algorithms."
authors = ["NiaOrg <niapy.organization@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/NiaOrg/NiaPy"
repository = "https://github.com/NiaOrg/NiaPy"
documentation = "https://niapy.org/en/stable/"
keywords = ["nature-inspired", "evolutionary", "optimization"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.26.1"
pandas = "^2.1.1"
openpyxl = "^3.1.2"
matplotlib = "^3.8.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
pytest-randomly = "^3.15.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-rtd-theme = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
